### ISSUE TITLE
Add Actionscript and Flash

### ISSUE THREAD

**Issue by Prid13** [anderspk/itjobbtrender#3]
Hi!

Would you mind adding 'Actionscript' and 'Flash' keywords to the list? I'm a veteran Flash developer and am currently living off of Flash-related work. Times are however a bit difficult for someone as passionate and persistent as me. I'm hoping to find a full-time Flash job I can land in Norway, to finally fulfill my dreams and aspirations of climbing the fjords and mountains and code in Actionscript at the summits :)

I regret to confess that my "modern" web technology skills are of questionable nature and I fear that if I fight this battle alone, I'll only cause a mess that is irreversible. I've tried embarking this dangerous quest on my own, but in the end, I had to raise the white flag, put my ego down, and humbly ask for someone else, someone brave and bold enough to take on this task, to do it in my stead!

Salute to the brave one who risks his/her soul for me!

PS: Writing this "issue" alone has drained me of my newfound confidence to navigate the web of tomorrow. Please help me realize my dream before the sand stops flowing!

**Comment by Prid13** [comment]
What in the name of God Almighty has exactly transpired here? I come with humility and my arms up in the air, asking for immediate assistance with a pure heart lest my figurative life perishes. Yet, I am met with premature closure without warning, and no form of explanation, nor redirection to other means of help. All I am faced with is a patronizing sun, seemingly taunting my livelihood for nothing that it's worth, and though it may be true, even _I_ deserve the right to dignity, good sir.

I'd like to reiterate that my needs are of utmost importance as they depend on my survival. So, I kindly ask this "issue" to be reinstated. Thank you!

**Comment by anderspk** [comment]
I regret to inform you that your request to have "actionscript" added to the list has been denied. Have a nice day, ma'am.

**Comment by Prid13** [comment]
I feel as though every fiber of my soul has been tarnished!

Translator's Note: **triggered**
